backend:
  name: git-gateway
  branch: master
  squash_merges: true

media_folder: static/img
public_folder: /img

display_url: changeme

collections:
  - name: 'navigation'
    label: 'Navigation'
    files:
      - file: 'src/pages/navBar/index.md'
        label: 'Navbar'
        name: 'navbar'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'navbar',
            }
          - {
              label: 'Logo Image',
              name: 'logoImage',
              widget: 'object',
              fields:
                [
                  { label: 'Image', name: 'image', widget: 'image' },
                  {
                    label: 'Image Description',
                    name: 'imageAlt',
                    widget: 'string',
                  },
                ],
            }
          - {
              label: 'Menu Items',
              name: 'menuItems',
              widget: 'list',
              fields:
                [
                  { label: 'Label', name: 'label', widget: 'string' },
                  {
                    label: 'Link Type',
                    name: 'linkType',
                    widget: 'select',
                    options: ['internal', 'external'],
                  },
                  {
                    label: 'Link URL',
                    name: 'linkURL',
                    widget: 'string',
                    hint: 'Use a relative URL (e.g. /about) if the link is an internal link.',
                  },
                ],
            }
      - file: 'src/pages/footer/index.md'
        label: 'Footer'
        name: 'footer'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'footer',
            }
          - {
              label: 'Social Links',
              name: 'socialUrls',
              widget: 'list',
              fields:
                [{ label: 'Link URL', name: 'linkURL', widget: 'string' }],
            }
          - { label: Copyright Holder, name: copyrightHolder, widget: string }
      - file: 'src/pages/announcementBar/index.md'
        label: 'Announcement Bar'
        name: 'announcementBar'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'announcement-bar',
            }
          - { label: Turn Off, name: disabled, widget: boolean }
          - { label: Message, name: message, widget: string }
          - {
              label: Link,
              name: linkURL,
              widget: string,
              hint: 'Use a relative URL (e.g. /about) if the link is an internal link.',
            }
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/forms/index.md'
        label: Forms
        name: forms
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'forms-page',
            }
          - {
              label: SEO,
              name: seo,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: string },
                  { label: Browser Title, name: browserTitle, widget: string },
                ],
            }
          - {
              label: Forms,
              name: forms,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: string },
                  { label: Description, name: description, widget: string },
                  { label: File, name: file, widget: file },
                ],
            }
      - file: 'src/pages/home/index.md'
        label: 'Home'
        name: 'home'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'home-page',
            }
          - {
              label: SEO,
              name: seo,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: string },
                  { label: Browser Title, name: browserTitle, widget: string },
                ],
            }
          - {
              label: Hero,
              name: hero,
              widget: object,
              fields:
                [
                  { label: Image, name: imageSrc, widget: image },
                  { label: Image Description, name: imageAlt, widget: string },
                  { label: Button Text, name: getStarted, widget: string },
                ],
            }
          - {
              label: Therapy,
              name: therapy,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Content, name: content, widget: markdown },
                ],
            }
          - {
              label: Fees,
              name: fees,
              widget: object,
              fields:
                [
                  {
                    label: Family/Couple Pricing,
                    name: family,
                    widget: number,
                  },
                  { label: Individual Pricing, name: family, widget: number },
                  {
                    label: Link for Insurrance,
                    name: insurranceHref,
                    widget: string,
                  },
                  {
                    label: Text for Insurance Link,
                    name: insuranceMessage,
                    widget: string,
                  },
                ],
            }
          - {
              label: Sarah,
              name: sarah,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Image, name: imageSrc, widget: image },
                  { label: Image Description, name: imageAlt, widget: string },
                  { label: Content, name: content, widget: markdown },
                ],
            }
          - {
              label: Fit,
              name: fit,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Image, name: imageSrc, widget: image },
                  { label: Image Description, name: imageAlt, widget: string },
                  { label: Content, name: content, widget: markdown },
                ],
            }
