backend:
  name: git-gateway
  branch: master
  squash_merges: true

media_folder: static/img
public_folder: /img

display_url: changeme

collections:
  - name: 'navigation'
    label: 'Navigation'
    files:
      files:
        - file: 'src/pages/announcementBar/index.md'
          label: 'Announcement Bar'
          name: 'announcementBar'
          fields:
            - {
                label: 'Template Key',
                name: 'templateKey',
                widget: 'hidden',
                default: 'announcement-bar',
              }
            - { label: Message, name: message, widget: string }
            - {
                label: Link,
                name: linkURL,
                widget: string,
                hint: 'Use a relative URL (e.g. /about) if the link is an internal link.',
              }
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/home/index.md'
        label: 'Home'
        name: 'home'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'home-page',
            }
          - {
              label: SEO,
              name: seo,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: string },
                  { label: Browser Title, name: browserTitle, widget: string },
                ],
            }
